# Your project's server will run on localhost:xxxx at this port
URL: "theme-development.dev"

# Autoprefixer will make sure your CSS works with these browsers
BROWSERS:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# Gulp will reference these paths when it copies files
PATHS:
  # Paths to PHP files
  php:
    - "./*.php"
    - "./**/*.php"

  # Paths to images
  icons: "assets/img/svg-icons/*.svg"

  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"

  # Paths to JavaScript libraries, which are combined into one file
  javascript:
    # Libraries required by Foundation
    - "node_modules/what-input/dist/what-input.js"

    # Core Foundation files
    - "node_modules/foundation-sites/dist/js/plugins/foundation.core.js"
    - "node_modules/foundation-sites/dist/js/plugins/foundation.util.*.js"

    # Individual Foundation components
    # If you aren't using a component, just remove it from the list
    # - "node_modules/foundation-sites/dist/js/plugins/foundation.abide.js"
    # - "node_modules/foundation-sites/dist/js/plugins/foundation.accordion.js"
    # - "node_modules/foundation-sites/dist/js/plugins/foundation.accordionMenu.js"
    - "node_modules/foundation-sites/dist/js/plugins/foundation.drilldown.js"
    # - "node_modules/foundation-sites/dist/js/plugins/foundation.dropdown.js"
    - "node_modules/foundation-sites/dist/js/plugins/foundation.dropdownMenu.js"
    - "node_modules/foundation-sites/dist/js/plugins/foundation.equalizer.js"
    # - "node_modules/foundation-sites/dist/js/plugins/foundation.interchange.js"
    # - "node_modules/foundation-sites/dist/js/plugins/foundation.magellan.js"
    - "node_modules/foundation-sites/dist/js/plugins/foundation.offcanvas.js"
    # - "node_modules/foundation-sites/dist/js/plugins/foundation.orbit.js"
    - "node_modules/foundation-sites/dist/js/plugins/foundation.responsiveMenu.js"
    # - "node_modules/foundation-sites/dist/js/plugins/foundation.responsiveToggle.js"
    # - "node_modules/foundation-sites/dist/js/plugins/foundation.reveal.js"
    # - "node_modules/foundation-sites/dist/js/plugins/foundation.slider.js"
    # - "node_modules/foundation-sites/dist/js/plugins/foundation.sticky.js"
    # - "node_modules/foundation-sites/dist/js/plugins/foundation.tabs.js"
    # - "node_modules/foundation-sites/dist/js/plugins/foundation.toggler.js"
    # - "node_modules/foundation-sites/dist/js/plugins/foundation.tooltip.js"
    # - "node_modules/foundation-sites/dist/js/plugins/foundation.zf.responsiveAccordionTabs.js"

    # Paths to your custom JS are here
    - "assets/js/vendor/*.js"
    - "assets/js/theme/theme.js"

# Used in the theme .pot file for translation
POT:
  domain: 'croft'
  package: 'croft'


# Theme strings used in the `rename` gulp task
THEME:
  ## The current strings in the theme
  CURRENT:
    name: "Croft"
    slug: "croft"
    prefix: "croft_"
  ## The strings to rename in the theme
  NEW:
    name: "Croft"
    slug: "croft"
    prefix: "croft_"